### PR TITLE
OLMIS-2526 create demo data for lot, trade item and identifier

### PR DESCRIPTION
**Pull request by pengisgood**
Refer to: https://openlmis.atlassian.net/browse/OLMIS-2526

### CODE REVIEW

**Comment by joshzamor** [comment]
@pgesek :  could you or someone at SD review and merge this?  I think you're closer in timezone.

**Comment by joshzamor** [comment]
Holding on merge until screen-casting is done on test env.

Also to note, the identifiers table will be renamed:  https://openlmis.atlassian.net/browse/OLMIS-1696?focusedCommentId=38228&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38228

**Comment by pengisgood** [comment]
@joshzamor do you mean we need to change table name from 
`identifiers` to `orderable_identifiers`?

**Comment by joshzamor** [comment]
I think I just did something dumb, throwing this away and starting it again so it's clean.

**Pull request closed without merging**
